
#This script finds the most common significantly changing attributes within each list

```{r setup, include=FALSE}
library(waffle)
library(ggthemes)
library(ggplot2)
library(tidyverse)
library(kableExtra)
library(readxl)
library(directlabels)
library(ggrepel)
library(showtext)
library(hrbrthemes)
library(ggalt)
library(remotes)





```



```{r}


font_add_google(name = "Roboto", family = "roboto")
showtext_auto()


```




```{r}
# define a bunch of colors that follow IDEA's definitions ####
# basic pallette
# teal, green, magenta, yellow, indigo, orange
idea_colours <- c("#20B6E8","#8CCAAE","#E62D5F","#FFDD00","#43358B","#EB6209", "#336A97")

# democratic performance colors
# green, green, green, blue, orange
demperf_colours <- c("#8CCAAE","#a3d4be","#badfce","#336A97","#EB6209")

# regime classification colours
# basic version of the demperf colours
regime_colours <- demperf_colours[c(1,4,5)]

# colors for showing indicator performance levels
traffic_colours <- idea_colours[c(2,4,3)]

# colors for advancers and decliners
adv_decl_colours <- c("#890A3E", "#004587")

```




```{r}
indices <- read_csv("GSODI Long v5 (1975-2020).csv")

head(indices)

```


```{r}



#start with recovered backsliders, identify common changes

#read in data
survived <- read_csv("backsliding_recovery.csv")



#add in the years they began backsliding

survived$first_year <- c(2013, 2018, 2014)


survived$ID_year <- c(2017, 2020, 2017)

survived 

write_csv(survived, "survived_backsliding.csv")


```







```{r}

#find relevant rows
for (country in survived$ID_country_name) {

    f_year = survived$first_year[survived$ID_country_name == country]
    n_year = survived$ID_year[survived$ID_country_name == country]
    
   
    
  slice <- subset(indices, ID_country_name == country & (ID_year >= f_year & ID_year <= n_year))
 slice <- subset(slice, pos_sig_1_years == 1)
  
  head(slice)
  
  
  
  
  if (country == "North Macedonia") {
    nm <- slice
  }
  
   if (country == "Ukraine") {
    ukraine <- slice
   }
  
   if (country == "Romania") {
    romania <- slice
   }
  
}


back_recover <- rbind(nm, ukraine, romania)

back_recover
  
back_recover <- back_recover %>% group_by(ID_variable_name, ID_country_name) %>% mutate(count_country = n())


back_recover <- back_recover %>% group_by(ID_variable_name) %>% mutate(count_total = n())

back_recover <- subset(back_recover,count_total > 1 & (count_total > count_country))

back_recover <- select(back_recover,  ID_country_name, ID_year, ID_variable_name, pos_sig_1_years, neg_sig_1_years, count_total, count_country)


back_recover <- back_recover[order(-back_recover$count_total),]



#none shared between all 3, judicial indepenedence is most popular
     


```

```{r}


#create graph of most popular advancers



ggplot(back_recover, aes(x = ID_variable_name, count_total, y = count_total, fill = ID_country_name)) + geom_col(position = "dodge")    + scale_fill_manual(values = idea_colours) + theme_minimal() + # remove chart junk
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.ticks = element_line()) +
  theme(legend.title = element_blank()) + # remove legend title
  theme(legend.position = "bottom") + # move legend to bottom
  labs(title = "Most common advancers among countries recovered from backslding, 2000-2020", # add labels
       subtitle = "During period of backsliding",
       x = "", y = "Count", caption = 
  "Source: International IDEA, The Global State of Democracy Indices, 1975-2020")  + theme(text=element_text(size=8, family="roboto"), legend.position="bottom")



ggsave("Gelman_Advancers_Recovered_Backsliding.pdf", width = 9, height = 6, units = "in")


```



```{r}
#waffle plpt
new_slice


ggplot(back_recover, aes(values = pos_sig_1_years, fill = ID_country_name)) +
  geom_waffle(color = "white", size = .25, n_rows = 2, flip = TRUE) +
  facet_wrap(~ID_variable_name , nrow = 1, strip.position = "bottom") +
  labs(
    title = "Most common advancing attributes during period of backsliding",
    subtitle = "Each box represents a country",
    caption = caption) +   scale_x_discrete()  +
   guides(fill = guide_legend(ncol = 2)) +
  coord_equal() +
  scale_fill_manual(values = color_pallete) +  scale_y_continuous("Num. advancing subattributes",
                     labels = function(x) x * 2, # make this multiplyer the same as n_rows
                     expand = c(0,0)) + theme_minimal() +
  theme(text = element_text(size=10, family = "roboto"), 
        legend.title=element_blank(), 
        legend.text=element_text(size=rel(.5)),
        legend.position="right", 
        legend.key.width = unit(.3,  unit = "cm"),
        legend.spacing.x = unit(0, unit = "cm"),
        #legend.box.margin=margin(-12,-12,-12,-12), 
        
        axis.title.x=element_blank(),  
        axis.title.y = element_blank(),
        
        axis.ticks = element_blank(),
        axis.text =element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(),
        
        plot.title = element_text(size = rel(1), face = "bold", hjust = 0, margin = margin(0,0,5,0)),
        plot.subtitle = element_text(size = rel(.75), face = "plain", hjust = 0, margin = margin(0,0,5,0)),
        plot.caption = element_text(size = rel(0.5), face = "italic", hjust = 1, vjust = 1, margin = margin(12,0,0,0)),
        
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())


ggsave("Gelman_backslide_recovery_waffle.pdf", width = 9, height = 6, units = "in") # save your plot as a png

```








```{r}

#next, work with 2020 backsliders

#read in data
no_recover <- read_csv("backslide.csv")

no_recover





```





```{r}

#find relevant rows
mat = matrix(ncol = 0, nrow = 0)
  
# converting the matrix to data 
# frame
current_backslide=data.frame(mat)

no_recover
#find relevant rows
for (country in no_recover$ID_country_name) {

    f_year = no_recover$first_year_of_backslide[no_recover$ID_country_name == country]
 slice <- subset(indices, ID_country_name == country & (ID_year >= f_year))
 slice <- subset(slice,  neg_sig_1_years == 1)
 
  
 current_backslide <- rbind(slice, current_backslide)
}

current_backslide
  
```


```{r}
 current_backslide_save <- current_backslide %>% group_by(ID_country_name) %>% mutate(min_year = min(ID_year), max_year = 2020)

current_backslide_save <- distinct(current_backslide_save, ID_country_name, min_year, max_year)


current_backslide_save


write_csv(current_backslide_save, "2020_backsliders_years.csv")


```






```{r}
# identify common decliners



current_backslide <- current_backslide %>% group_by(ID_variable_name, ID_country_name) %>% mutate(count_country = n())


current_backslide <- current_backslide %>% group_by(ID_variable_name) %>% mutate(count_total = n())

current_backslide <- subset(current_backslide,count_total > 1 & (count_total > count_country))

current_backslide <- select(current_backslide,  ID_country_name, ID_year, ID_variable_name, neg_sig_1_years, count_total, count_country)


current_backslide <- current_backslide[order(-current_backslide$count_total),]

current_backslide



#civil liberties, freedom of expression, clean elections, freedom of movement are most popular decliners

```



```{r}

#create graph of most popular decliners
current_backslide_graph <- subset(current_backslide, count_total > 2)



ggplot(current_backslide_graph, aes(x = ID_variable_name, count_total, y = count_total, fill = ID_country_name)) + geom_col(position = "dodge")    + scale_fill_manual(values = idea_colours) + theme_minimal() + # remove chart junk
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.ticks = element_line()) +
  theme(legend.title = element_blank()) + # remove legend title
  theme(legend.position = "bottom") + # move legend to bottom
  labs(title = "Most common decliners among countries backsliding in 2020", # add labels
       subtitle = "During period of backsliding",
       x = "", y = "Count", caption = 
  "Source: International IDEA, The Global State of Democracy Indices, 1975-2020")  + theme(text=element_text(size=8, family="roboto"), legend.position="bottom")



ggsave("Gelman_Decliners_2020_Backsliding.pdf", width = 9, height = 6, units = "in")

```





```{r}
#waffle plot

current_backslide_graph

ggplot(current_backslide_graph, aes(values = neg_sig_1_years, fill = ID_country_name)) +
  geom_waffle(color = "white", size = .25, n_rows = 2, flip = TRUE) +
  facet_wrap(~ID_variable_name , nrow = 1, strip.position = "bottom") +
  labs(
    title = "Most common decliners among countries backsliding in 2020 during period of backsliding",
    subtitle = "Each box represents a country",
    caption = caption) +   scale_x_discrete()  +
   guides(fill = guide_legend(ncol = 2)) +
  coord_equal() +
  scale_fill_manual(values = color_pallete) +  scale_y_continuous("Num. declining subattributes",
                     labels = function(x) x * 2, # make this multiplyer the same as n_rows
                     expand = c(0,0)) + theme_minimal() +
  theme(text = element_text(size=8, family = "roboto"), 
        legend.title=element_blank(), 
        legend.text=element_text(size=rel(.5)),
        legend.position="right", 
        legend.key.width = unit(.3,  unit = "cm"),
        legend.spacing.x = unit(0, unit = "cm"),
        #legend.box.margin=margin(-12,-12,-12,-12), 
        
        axis.title.x=element_blank(),  
        axis.title.y = element_blank(),
        
        axis.ticks = element_blank(),
        axis.text =element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(),
        
        plot.title = element_text(size = rel(1), face = "bold", hjust = 0, margin = margin(0,0,5,0)),
        plot.subtitle = element_text(size = rel(.75), face = "plain", hjust = 0, margin = margin(0,0,5,0)),
        plot.caption = element_text(size = rel(0.5), face = "italic", hjust = 1, vjust = 1, margin = margin(12,0,0,0)),
        
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

ggsave("Gelman_still_backsliding_waffle.pdf", width = 9, height = 6, units = "in") # save your plot as a png

```












```{r}
#do the same for survivors of breakdown

#read in data
surv_breakdown <- read_csv("survived_breakdown.csv")

surv_breakdown
```



```{r}
surv_breakdown_save <- surv_breakdown %>% group_by(ID_country_name) %>% mutate(min_year = min(ID_year), max_year = max(ID_year))

surv_breakdown_save <- distinct(surv_breakdown_save, ID_country_name, min_year, max_year)


surv_breakdown_save


write_csv(surv_breakdown_save, "survived_breakdown_years.csv")


```


```{r}

#find relevant rows

mat = matrix(ncol = 0, nrow = 0)
  
# converting the matrix to data 
# frame
surv_breakdown_graph=data.frame(mat)



for (country in unique(surv_breakdown_save$ID_country_name)) {

    f_year = min(surv_breakdown$ID_year[surv_breakdown$ID_country_name == country])
    l_year = max(surv_breakdown$ID_year[surv_breakdown$ID_country_name == country])
    
    slice <- subset(indices, ID_country_name == country & (ID_year >= f_year & ID_year <= l_year))
    slice <- subset(slice,  pos_sig_1_years == 1 )
 
  
 surv_breakdown_graph <- rbind(slice, surv_breakdown_graph)
}

surv_breakdown_graph
  
  



```



```{r}

#identify common decliners
surv_breakdown_graph <- surv_breakdown_graph %>% group_by(ID_variable_name, ID_country_name) %>% mutate(count_country = n())

surv_breakdown_graph <- surv_breakdown_graph %>% group_by(ID_variable_name) %>% mutate(count_total = n())

surv_breakdown_graph <- subset(surv_breakdown_graph,count_total > 1 & (count_total > count_country))

surv_breakdown_graph <- select(surv_breakdown_graph,  ID_country_name, ID_year, ID_variable_name, pos_sig_1_years, count_total, count_country)


surv_breakdown_graph <- surv_breakdown_graph[order(-surv_breakdown_graph$count_total),]



surv_breakdown_graph

#clean elections, representative government, effective parliment, elected government, checks on gov, freedom of association and assembly, free political parties
```
```{r}


#create graph of most popular decliners
surv_breakdown_graph <- subset(surv_breakdown_graph, count_total > 4)



ggplot(surv_breakdown_graph, aes(x = ID_variable_name, count_total, y = count_total, fill = ID_country_name)) + geom_col(position = "dodge")    + theme_minimal() + # remove chart junk
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.ticks = element_line()) +
  theme(legend.title = element_blank()) + # remove legend title
  theme(legend.position = "bottom") + # move legend to bottom
  labs(title = "Most common advancers among countries recovered from breakdown 2000-2020", # add labels
       subtitle = "During period of breakdown",
       x = "", y = "Count", caption = 
  "Source: International IDEA, The Global State of Democracy Indices, 1975-2020")  + theme(text=element_text(size=8, family="roboto"), legend.position="bottom")


ggsave("Gelman_Advancerss_Recovered_Breakdown.pdf", width = 9, height = 6, units = "in")


```


```{r}
#waffle plot


surv_breakdown_graph <- subset(surv_breakdown_graph, count_total > 4)
surv_breakdown_graph
ggplot(surv_breakdown_graph, aes(values = pos_sig_1_years, fill = ID_country_name)) +
  geom_waffle(color = "white", size = .25, n_rows = 2, flip = TRUE) +
  facet_wrap(~ID_variable_name , nrow = 1, strip.position = "bottom") +
  labs(
    title = "Most common advancing attributes during period of breakdown for recovered countries",
    subtitle = "Each box represents a country",
    caption = caption) +   scale_x_discrete()  +
   guides(fill = guide_legend(ncol = 2)) +
  coord_equal() +
  scale_fill_manual(values = color_pallete) +  scale_y_continuous("Num. advancing subattributes",
                     labels = function(x) x * 2, # make this multiplyer the same as n_rows
                     expand = c(0,0)) + theme_minimal() +
  theme(text = element_text(size=7, family = "roboto"), 
        legend.title=element_blank(), 
        legend.text=element_text(size=rel(.5)),
        legend.position="right", 
        legend.key.width = unit(.3,  unit = "cm"),
        legend.spacing.x = unit(0, unit = "cm"),
        #legend.box.margin=margin(-12,-12,-12,-12), 
        
        axis.title.x=element_blank(),  
        axis.title.y = element_blank(),
        
        axis.ticks = element_blank(),
        axis.text =element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(),
        
        plot.title = element_text(size = rel(1), face = "bold", hjust = 0, margin = margin(0,0,5,0)),
        plot.subtitle = element_text(size = rel(.75), face = "plain", hjust = 0, margin = margin(0,0,5,0)),
        plot.caption = element_text(size = rel(0.5), face = "italic", hjust = 1, vjust = 1, margin = margin(12,0,0,0)),
        
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())


ggsave("Gelman_breakdown_recovered_waffle.pdf", width = 9, height = 6, units = "in") # save your plot as a png
```








```{r}
#do the same for countries that did not recover from their breakdown




mat = matrix(ncol = 0, nrow = 0)
  
# converting the matrix to data 
# frame
broken =data.frame(mat)

countries <- read_csv("breakdown.csv")

countries

broken <- subset(indices, ID_country_name %in% countries$breakdown_list & ID_year >= 2000)


broken <- subset(broken, (regime_status_change_1_year == -1 & regime_status_name == "Hybrid Regime") | (regime_status_change_1_year == 1 & regime_status_name == "Democracy") | (regime_status_change_1_year == -2 ) | (regime_status_change_1_year == 2 ))


broken <- distinct(broken, ID_country_name, regime_status_name, ID_year,.keep_all = TRUE)



broken <- select(broken, ID_country_name, regime_status_name, ID_year, regime_status_change_1_year)

broken

```



















```{r}


#define boundry years as most recent democratic transition and most recent transition away from democracy
for (country in unique(broken$ID_country_name)) {
  dem = subset(indices, ID_country_name == country & regime_status_name == "Democracy" & regime_status_change_1_year > 0)
  not_dem  = subset(indices, ID_country_name == country & ((regime_status_name == "Hybrid Regime" & regime_status_change_1_year == -1) | (regime_status_name == "Authoritarian Regime" & regime_status_change_1_year == -2)))
  dyear = max(dem$ID_year)
  not_dem_year = max(not_dem$ID_year)
  
 broken$last_dem_year[broken$ID_country_name == country] = dyear
 
 broken$not_dem_year[broken$ID_country_name == country] = not_dem_year
  
  
  
  
  
}


broken
```




```{r}
broken

broken_save <- distinct(broken, ID_country_name, last_dem_year, not_dem_year)

broken_save



write_csv(broken_save, "broken_years.csv")


```



```{r}

#find relevant rows

mat = matrix(ncol = 0, nrow = 0)
  
# converting the matrix to data 
# frame
broken_data=data.frame(mat)


#find relevant rows
for (country in unique(broken$ID_country_name)) {

    f_year = min(broken$last_dem_year[broken$ID_country_name == country])
    l_year = max(broken$not_dem_year[broken$ID_country_name == country])
    
    slice <- subset(indices, ID_country_name == country & (ID_year >= f_year & ID_year <= l_year))
    slice <- subset(slice,  neg_sig_1_years == 1)
 
  
 broken_data <- rbind(slice, broken_data)
}

broken_data
  
  
```
```{r}
#identify common decliners

broken_data <- broken_data %>% group_by(ID_variable_name, ID_country_name) %>% mutate(count_country = n())


broken_data <- broken_data %>% group_by(ID_variable_name) %>% mutate(count_total = n())

broken_data <- subset(broken_data,count_total > 1 & (count_total > count_country))

broken_data <- select(broken_data,  ID_country_name, ID_year, ID_variable_name, neg_sig_1_years, count_total, count_country)


broken_data <- broken_data[order(-broken_data$count_total),]

broken_data

#clean elections,  effective parliment, judicial independence, most popular decliners

```



```{r}



#create graph of most popular decliners
broken_data_new <- subset(broken_data, count_total > 10)

#broken_data_new <- broken_data

ggplot(broken_data_new, aes(x = ID_variable_name, count_total, y = count_total, fill = ID_country_name)) + geom_col(position = "dodge")    + theme_minimal() + # remove chart junk
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.ticks = element_line()) +
  theme(legend.title = element_blank()) + # remove legend title
  theme(legend.position = "bottom") + # move legend to bottom
  labs(title = "Most common decliners among all countries that broke down 2000-2020", # add labels
       subtitle = "During period of breakdown",
       x = "", y = "Count", caption = 
  "Source: International IDEA, The Global State of Democracy Indices, 1975-2020")  + theme(text=element_text(size=8, family="roboto"), legend.position="bottom")


ggsave("Gelman_Decliners_NoRecovery_Breakdown.pdf", width = 9, height = 6, units = "in")


```
```{r}


#waffle plot
broken_data_new

ggplot(broken_data_new, aes(values = neg_sig_1_years, fill = ID_country_name)) +
  geom_waffle(color = "white", size = .25, n_rows = 2, flip = TRUE) +
  facet_wrap(~ID_variable_name , nrow = 1, strip.position = "bottom") +
  labs(
    title = "Most common declining attributes during period of breakdown",
    subtitle = "Each box represents a country",
    caption = caption) +   scale_x_discrete()  +
   guides(fill = guide_legend(ncol = 2)) +
  coord_equal()  +  scale_y_continuous("Num. declining subattributes",
                     labels = function(x) x * 2, # make this multiplyer the same as n_rows
                     expand = c(0,0)) + theme_minimal() +
  theme(text = element_text(size=7, family = "roboto"), 
        legend.title=element_blank(), 
        legend.text=element_text(size=rel(.5)),
        legend.position="right", 
        legend.key.width = unit(.3,  unit = "cm"),
        legend.spacing.x = unit(0, unit = "cm"),
        #legend.box.margin=margin(-12,-12,-12,-12), 
        
        axis.title.x=element_blank(),  
        axis.title.y = element_blank(),
        
        axis.ticks = element_blank(),
        axis.text =element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(),
        
        plot.title = element_text(size = rel(1), face = "bold", hjust = 0, margin = margin(0,0,5,0)),
        plot.subtitle = element_text(size = rel(.75), face = "plain", hjust = 0, margin = margin(0,0,5,0)),
        plot.caption = element_text(size = rel(0.5), face = "italic", hjust = 1, vjust = 1, margin = margin(12,0,0,0)),
        
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())


ggsave("Gelman_breakdown_no_recovery_waffle.pdf", width = 9, height = 6, units = "in") # save your plot as a png

```


